apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ default .Values.service.port .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}
