namespace: staging
name: techtrends
replicaCount: 3
service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
image:
  repository: yourdockerhubusername/techtrends
  tag: latest
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"
containerPort: 3111
livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz

